### ISSUE TITLE
FedGMM复现

### ISSUE THREAD

**Issue by jxthyatt** [TsingZ0/PFLlib#140]
你好，可以复现FedGMM（Personalized Federated Learning under Mixture of Distributions）这个工作吗？原作者的代码有问题

**Comment by TsingZ0** [comment]
我最近deadline比较多，得看其他同学有没有时间复现一下

**Comment by TsingZ0** [comment]
本平台比较容易扩展新算法，可以参考[这里](https://github.com/TsingZ0/PFL-Non-IID#easy-to-extend)或Figure 1进行扩展。
