### ISSUE TITLE
Model-heterogenous methods

### ISSUE THREAD

**Issue by briannamueller** [TsingZ0/PFLlib#154]
For knowledge-distillation based methods that allow heterogenous client models such as FedKD , FML, and FedProto, does this code base support the functionality to run experiments where clients have different local model architectures?

**Comment by TsingZ0** [comment]
This codebase does not naturally support heterogeneous models. Please refer to our [HtFL](https://github.com/TsingZ0/HtFL) project, which is built on this codebase. 

We have already mentioned this in the README file. :-)

**Comment by briannamueller** [comment]
apologies for missing that, thank you!
