### ISSUE TITLE
关于FML和FedKD算法的复现问题。

### ISSUE THREAD

**Issue by syq1175554320** [TsingZ0/PFLlib#155]
您好，我尝试在不同指标下对提供的几种常见数据集按迪利克雷分布划分，在FML和FedKD算法中发现把异构程度变大，精度反而上升；而把异构程度降低，精度反而下降，想请教这是什么问题，在其他算法中没遇到这种情况，希望您看到后有时间回答一下，谢谢。

**Comment by TsingZ0** [comment]
因为我这里对于FML和FedKD都用的是个性化联邦学习的评测方法，个性化联邦学习方法是会出现你说的这种情况，大多数个性化联邦学习都不适用于异构程度低的场景。因为他们过分地关注个性化而忽略了泛化，具体可以参考我的几篇论文里的[实验结果和讨论](https://github.com/TsingZ0/PFLlib#experimental-results)

**Comment by syq1175554320** [comment]
原来是这样，感谢您的指教！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TsingZ0/PFLlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TsingZ0/PFLlib] 关于FML和FedKD算法的复现问题。 (Issue #155)





 
因为我这里对于FML和FedKD都用的是个性化联邦学习的评测方法，个性化联邦学习方法是会出现你说的这种情况，大多数个性化联邦学习都不适用于异构程度低的场景。因为他们过分地关注个性化而忽略了泛化，具体可以参考我的几篇论文里的实验结果和讨论
