### ISSUE TITLE
使用DLG梯度泄漏攻击来测试算法的隐私保护能力是否合理？

### ISSUE THREAD

**Issue by FryLcm** [TsingZ0/PFLlib#161]
我对梯度泄漏攻击的理解是：现有的梯度泄露攻击方法要想攻击成功，客户端都得满足梯度只更新一次。比如我本地有1000张图片，一次输入给模型10张，也就是要输入100次，每次输入后梯度都要正向传播和反向传播。但现有的梯度泄露攻击只能满足输入一次才能攻击成功，只要输入多次的话，就不能攻击成功了。
尤其是在您的论文中PSNR值均为小于10的，而PSNR值低于20dB的话说明图像质量不可接受，说明这样恢复的图片应该是乱码的，推导不出原始图片信息。同时，我使用了您的代码进行测试，发现并不是说GPFL算法和FedCP算法的PSNR值就低于Fedavg算法的。

**Comment by TsingZ0** [comment]
在该项目中，我们参考[FedCG](https://www.ijcai.org/proceedings/2022/0324.pdf)引入了DLG攻击，具体做法和原理请参考该论文。

PSNR值的测试，主要是看同等数量的communication iteration过后的PSNR的值。
