### ISSUE TITLE
python generate_tiny_imagenet.py noniid - pat训练产生样本数量是相同的

### ISSUE THREAD

**Issue by PaiStardian** [TsingZ0/PFLlib#162]
class_per_client=10设置为10时，出现这个问题 ![1704810264925](https://github.com/TsingZ0/PFLlib/assets/130040341/5136eb54-6ed0-41c3-9cd8-5c8a7742ee78)

**Comment by PaiStardian** [comment]
![1704810402979](https://github.com/TsingZ0/PFLlib/assets/130040341/826fe7a9-e786-486c-b6ec-9f005903c599)

**Comment by TsingZ0** [comment]
这是正常的，因为20个clients, class_per_client=10设置为10时，会使得一个类别的数据完全地分配给某个client。而tiny-imagenet里每个类的数据量都是固定的，这就导致client上的数据量都相同。此时即使设置unbalanced，也无济于事。

要实现unbalanced，class_per_client>10比较合理，设置为20比较合适。
