### ISSUE TITLE
agnews - dir alpha = 0.1时 运行FedALA出现错误

### ISSUE THREAD

**Issue by PaiStardian** [TsingZ0/PFLlib#165]
你好 ，Algorithm: FedALA
Local batch size: 64
Local steps: 10
Local learing rate: 0.01
Local learing rate decay: False
Total number of clients: 20
Clients join in each round: 1
Clients randomly join: False
Client drop rate: 0.0
Client select regarding time: False
Running times: 1
Dataset: agnews
Number of classes: 4
Backbone: fastText
Using device: cuda
Using DP: False
Auto break: False
Global rounds: 500
Cuda device id: 0
DLG attack: False
Total number of new clients: 0
Fine tuning epoches on new clients: 0
[这是我设置的参数然后再运行时报错，请问这种错误应该如何解决
![1705415350774](https://github.com/TsingZ0/PFLlib/assets/130040341/3fe785f5-722f-47d2-9b1a-62ca8e8a9032)

**Comment by TsingZ0** [comment]
具体报了什么错误呢

**Comment by TsingZ0** [comment]
请问你是修改过ALA.py吗？line 142目前是`y = y.to(self.device)`

**Comment by PaiStardian** [comment]
你好 我更新了最新的代码还是报如下的错误

**Comment by PaiStardian** [comment]
您可以验证一下 
感谢

**Comment by TsingZ0** [comment]
由于后来修改了dataset的划分方式，允许sample数量小于batch size大小，所以造成了这里的报错。

设置line 91`rand_loader`里的`drop_last=False`就好了
