### ISSUE TITLE
关于join_ratio和client_drop_rate两个参数的区别

### ISSUE THREAD

**Issue by YrChenM** [TsingZ0/PFLlib#168]
请问这两个参数相对于全局模型有什么区别吗？我似乎没太看明白, 好像最后的效果都是只有一部分模型的参数参与全局模型聚合？

**Comment by TsingZ0** [comment]
语义不同，效果也不同。虽然从聚合结果来看是类似的，但`join_ratio<1`的话执行训练的client数量**减少**；而`1-client_drop_rate<1`的话执行训练的client数量**不变**，只是drop掉的client最后不参与聚合，也就是“白训练了”，这符合client drop的定义（存在client端训练资源的浪费）。
