### ISSUE TITLE
Training issue about pFedMe

### ISSUE THREAD

**Issue by Chen-Junbao** [TsingZ0/PFLlib#170]
After comparing your code with the [official code](https://github.com/CharlieDinh/pFedMe) released by the authors proposing pFedMe, I noticed a difference in server training.

Specifically, in line 53 of [serverpFedMe.py](https://github.com/CharlieDinh/pFedMe/blob/master/FLAlgorithms/servers/serverpFedMe.py) in the official repository, all clients update their local models. However, in line 60 of your [serverpFedMe.py](https://github.com/TsingZ0/PFLlib/blob/master/system/flcore/servers/serverpFedMe.py), only selected clients update their local model.

I checked the pseudocode of the paper, and it is true that all clients update their models and only selected clients send their local models.

<img width="730" alt="image" src="https://github.com/TsingZ0/PFLlib/assets/46412966/a00e3228-8032-4fa2-9cfe-4729f8b231eb">

I think that this issue can be fixed by changing self.selected_clients to all users, because the server only receives selected clients' models in receive_models function.

**Comment by TsingZ0** [comment]
First of all, PFLlib is **not built for the reproduction of algorithms' official results** but for a fair comparison of existing algorithms. Most FL algorithms assume partial client participation, which is also one of the requirements of FL algorithms according to the basic FL algorithm FedAvg. Thus, PFLlib adopts partial client participation for all algorithms. 

Second, an FL algorithm applies to various fundamental system settings, such as client selection strategies, total client numbers, tasks, model architectures, etc. These are hyperparameter settings of the FL system if this algorithm does not focus on specific settings.

**Comment by Chen-Junbao** [comment]
I see. Thank you for your reply.
