### ISSUE TITLE
resnet18训练Cifar100数据集准确率很低

### ISSUE THREAD

**Issue by Sputnik-12** [TsingZ0/PFLlib#172]
我在尝试与集中式训练对比时发现对于Cifar100数据集即使将客户端数量修改为1，使用FedAvg或Local算法训练resnet18模型，测试准确率始终难以超过50%甚至40%。而只有1个客户端的情况下直接加载原始的Cifar100数据集，不使用dataset文件夹下的代码，最终能达到65%左右的准确率。将Cifar100数据集先合并再全部分配给1个客户端再划分似乎比原始数据集的划分更容易过拟合，不能等效成集中式训练，不知道什么原因。

**Comment by TsingZ0** [comment]
这里的”对于Cifar100数据集即使将客户端数量修改为1“指的是用dataset文件夹下的代码切分数据集的时候，就设置为1个客户机吗？

我们这边默认设置数据量：tran set: test set=3:1，而且是先将train set和test set混合后再切分为3:1的。原始数据集tran set: test set=5:1，相比而言，训练集数据量更多，更不容易过拟合。

**Comment by polaris-973** [comment]
非常感谢作者的开源工作，真的帮助了我很多。
在此想请教一个问题，在实验中发现与使用4-layer CNN相比，换用ResNet进行相同数据集实验（Tiny-ImageNet）后非常容易发生过拟合而后出现性能明显下降，想请问作者一般在实践中如果想添加不同模型架构的实验时使用ResNet18这种相对而言复杂度明显变高的模型，在超参数选择上有什么经验性的建议以避免上述情况发生？
附实验细节：划分客户端数量: 20; batch_size: 64； lr: 0.005/0.1.
期待您的及时回复~

**Comment by TsingZ0** [comment]
很抱歉，超参数选择上，我这边给不了太多的建议。因为我在做研究的过程中，本着“尽可能不调参”、“尽可能在各种任务上只使用一套超参数”的理念，去设计联邦学习算法。

**Comment by polaris-973** [comment]
可能作者对我的提问有些误解，我想进一步补充问题背景。在使用您的开源代码进行相同数据集的实验时，以Ditto算法为例，不改动任何其它而只换用选用模型，即4-layer CNN -> ResNet18，性能会出现明显下降，而我在阅读您的相关论文时没有发现该情况的发生，所以想对此进行询问，是什么原因造成了该现象的发生？

**Comment by greenhead01** [comment]
> 我在尝试与集中式训练对比时发现对于Cifar100数据集即使将客户端数量修改为1，使用FedAvg或Local算法训练resnet18模型，测试准确率始终难以超过50%甚至40%。而只有1个客户端的情况下直接加载原始的Cifar100数据集，不使用dataset文件夹下的代码，最终能达到65%左右的准确率。将Cifar100数据集先合并再全部分配给1个客户端再划分似乎比原始数据集的划分更容易过拟合，不能等效成集中式训练，不知道什么原因。

你好，也是这个问题，请问最后是如何解决的？
