### ISSUE TITLE
converge 

### ISSUE THREAD

**Issue by jin-94** [TsingZ0/PFLlib#173]
![wen](https://github.com/TsingZ0/PFLlib/assets/96270979/3dec038b-04e1-4336-b4d2-0081b219a522)
![table](https://github.com/TsingZ0/PFLlib/assets/96270979/bbc44ced-aba9-42f9-839c-03ccea8f218c)

FedCP文章中计算通信开销时，指标为达到收敛时的迭代次数和时间。请问具体收敛的指标什么呢，在文中没有具体看到。the number of iterations required for each method to and calculate the average time consumption in each iteration

**Comment by TsingZ0** [comment]
当联邦学习系统总的目标损失（比如FedCP文中公式1中G函数的值）的值的变化趋于稳定，我们就认为联邦学习算法收敛。

**Comment by jin-94** [comment]
好的多谢解答
