### ISSUE TITLE
 2000 iterations 

### ISSUE THREAD

**Issue by jin-94** [TsingZ0/PFLlib#174]
We run all tasks up to 2000 iterations until all methods converge empirically。

FedCP论文中实验，请问所有的实验都是完成2000轮迭代吗？
本人也是在做一些实验复现学习，所以有些疑惑，希望可以解答，谢谢  ！ ！

**Comment by jin-94** [comment]
![1](https://github.com/TsingZ0/PFLlib/assets/96270979/7e575ae2-e659-46d0-9ad8-cc2dbd510c36)
在表4中验证可扩展性时，规律是N越大准确率会逐步降低。
但在表2中N=20的实验准确率是高于所有其他的参数设置的。
所以后面实验也是2000轮迭代吗？还是直到收敛时的准确率。

**Comment by TsingZ0** [comment]
> 所以后面实验也是2000轮迭代后最高准确率吗？

是的，因为超参数是在20个clients的场景下调的，其他场景下没调整了，所以在20个clients的场景中的acc比较好。当N不同的时候，其实整个联邦学习的场景设定就不同了，不同的N的场景下结果进行横向对比是没有意义的。可扩展性，主要是探索当N变大后，FedCP是否在跟SOTA方法对比上还有优势。
