### ISSUE TITLE
关于Flower102的划分

### ISSUE THREAD

**Issue by gebilxs** [TsingZ0/PFLlib#179]
想问一下在FedKtl中对于102的划分最终只测试了100类吗，使用平台的划分方式没有办法全部划分

**Comment by TsingZ0** [comment]
测试的是102类，使用本平台可以划分到全部的102类的（label从0到101）：
![image](https://github.com/TsingZ0/PFLlib/assets/24207672/8af66a15-b691-4b05-8ed8-d12640670042)
