### ISSUE TITLE
关于新客户端微调问题

### ISSUE THREAD

**Issue by fengkoushangdeZZX** [TsingZ0/PFLlib#180]
尊敬的作者您好，非常感激您的开源精神！我在用您的代码做实验时遇到了一个问题，就是我目前在尝试联邦域泛化方面的问题研究，在您的代码fine_tuning_new_clients()函数和test_metrics_new_clients()是否可以用作在未知域客户端的泛化测试？

**Comment by TsingZ0** [comment]
本身这两个函数就是为了在未知客户端上进行泛化测试（基于Shai Ben-David's Theorem）的，用法可以看我NeurIPS'23那篇[Eliminating Domain Bias for Federated Learning in Representation Space](https://arxiv.org/abs/2311.14975)的附录部分。不过至于域泛化，可能有该领域独有的验证泛化能力的方法。建议深入调研和确认后再使用

**Comment by fengkoushangdeZZX** [comment]
非常感谢您的回复，我去研读一下您的论文，感谢您的分享
