### ISSUE TITLE
关于Cifar100数据集运行报错的问题

### ISSUE THREAD

**Issue by SharonNightray** [TsingZ0/PFLlib#181]
您好，非常感谢您开源代码的帮助！我是一名初学者，在使用Cifar100数据集的时候运行出现了错误。我的设置是pat设置，共设置了20个客户端，每个客户端都拥有10类数据，但是在运行的时候仍然会出现
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
的错误，问题可能出现在哪里呢

**Comment by TsingZ0** [comment]
可能的问题是：1、你的数据经过Dataloader封装之后，这个batch里全部都是某个label的数据，2、你这个batch只有一个sample
