### ISSUE TITLE
Hyperparameter settings for some models

### ISSUE THREAD

**Issue by YouthBL** [TsingZ0/PFLlib#183]
Hi, Jianqing, thank you very much for your open-source project, it's great work and helped me a lot in my studies. Recently, I ran the FedRep and FedALA models on the Cifar10 dataset under the Pathological heterogeneous setting， the hyperparameters I used were  ''python main.py -lr 0.005 -lbs 10 -nc 20 -jr 1 -nb 10 -data Cifar10 -m cnn -algo FedXXX -gr 2000 -did 0''. The results are 91.14 for  FedRep and 91.75 for FedALA. There is a gap of about 0.7% compared to what is reported in Table 2 of the FedALA paper. So I want to ask for help on how to tune my hyperparameters.  Thanks again for the great work on the project.

**Comment by TsingZ0** [comment]
Thank you for your attention! As mentioned in the `README.md`, this project updates gradually, and some basic settings may also change, so the gap of 0.7% is negligible in this case. I typically use grid search to tune hyperparameters.

**Comment by YouthBL** [comment]
I got it. Thanks for your reply.
