### ISSUE TITLE
关于病态数据集划分时的问题

### ISSUE THREAD

**Issue by panjinkun** [TsingZ0/PFLlib#184]
您好，产生病态数据集时，剩下的数据会堆积到同一个客户端中
例如：Client 9         Size of data: 7737      Labels:  [0 1]
                 Samples of labels:  [(0, 3903), (1, 3834)]
和readme里不同
Client 9     Size of data: 4196  Labels:  [0. 1.]
Client 9     Samples of labels:  [(0, 652), (1, 3544)]
这个问题应该怎么解决？

**Comment by TsingZ0** [comment]
> 产生病态数据集时，剩下的数据会堆积到同一个客户端中
确实是会这样的，用来模拟某些客户机存在较多数据的unbalance场景。

readme里的数据划分只是提供一个例子，且是早期的PFLlib版本生成的，请以最新版本生成的结果为准。
