### ISSUE TITLE
请问怎么使用h5 文件？

### ISSUE THREAD

**Issue by maxwellgodv** [TsingZ0/PFLlib#192]

**Comment by maxwellgodv** [comment]
您好，我完成了一次训练，最终在 result 中得到了一个 h5 文件，请问如果我想要进行测试，应该怎么使用这个 h5 文件呢？

**Comment by TsingZ0** [comment]
h5文件存储了训练指标，使用h5文件的方式已经整合在代码里了，参见`main.py`的第375行
