### ISSUE TITLE
关于实验结果

### ISSUE THREAD

**Issue by Aaron2Woo** [TsingZ0/PFLlib#193]
感谢分享！跑出来的FedAvg@Cifar10的实验结果如下图，存在两个疑问：
1. 为什么在0-500次round精度均低于10%？
2. 为什么需要设置这么多的communication round才能收敛？

![123](https://github.com/TsingZ0/PFLlib/assets/75078201/bed54e79-ce99-45ad-8322-ff81bc3f9eab)

**Comment by TsingZ0** [comment]
具体的训练情况与具体场景超参数设置等都相关，并不会有一个稳定统一的表现，对于每个算法来说都是这样
