### ISSUE TITLE
Nohup run

### ISSUE THREAD

**Issue by gestefane** [TsingZ0/PFLlib#195]
Hi!
How to run with nohup and log to a file?
I want to log all scripts output results including time cost for each round. It appears that this information is not logged on MNIST_FedAvg_test_0.h5 file, for example.

I just tried using:
nohup python main.py -data MNIST -m cnn -algo FedAvg -gr 2000 -did 0 &
and the tule nohup.out always contains only one line with "ignoring input"

I tried using:
nohup python main.py -data MNIST -m cnn -algo FedAvg -gr 2000 -did 0 > nohup-test.out 2>&1 &

with same result for nohup-test.out file.

Thank you.

**Comment by TsingZ0** [comment]
You need to add `-u` after `python`, e.g., `nohup python -u main.py ...`, to directly print results to the file without using the buffer. Please see the `run_me.sh` files in [FedALA](https://github.com/TsingZ0/FedALA), [FedCP](https://github.com/TsingZ0/FedCP), [GPFL](https://github.com/TsingZ0/GPFL), and [DBE](https://github.com/TsingZ0/DBE) for examples.
