### ISSUE TITLE
我在使用系统默认的配置时，只修改了--client_drop_rate=0.9，即有90%节点白训练了，但是训练结果似乎没有变化

### ISSUE THREAD

**Issue by kyp2022** [TsingZ0/PFLlib#202]
我在使用系统默认的配置时，只修改了--client_drop_rate=0.9，即有90%节点白训练了，但是训练结果似乎没有变化

请问这是什么原因导致的？
是模型设计的太好了吗？

我将数据集划分1000份，只用100个客户端进行训练（每次采样0.3），同时也设置0.9的退出率，发现效果和0的退出率还是相差无几

请问应该修改哪些参数可以使得对比效果更明显。

**Comment by TsingZ0** [comment]
请问您用的是FedAvg算法吗
