### ISSUE TITLE
关于实现FEDPCL算法时，在client.train阶段时的交叉熵计算的两个参数

### ISSUE THREAD

**Issue by tuichong** [TsingZ0/PFLlib#203]
https://github.com/TsingZ0/PFLlib/blob/1ae0ff4b32b40fb3ead59c307046f4a7330cf339/system/flcore/clients/clientpcl.py#L77
您好！非常感谢您能分享这么优秀的项目，我受益匪浅。
我有一个关于您在实现FEDPCL算法时的一个疑问，在client.train阶段时的将similarity = torch.matmul(rep, global_protos_emb.T) / self.tau, L_g = self.loss(similarity, y)的疑惑，在计算交叉熵损失时使用similarity与标签直接进行损失计算，这是在特征向量与标签之间进行的吗？

**Comment by TsingZ0** [comment]
感谢关注！向量与矩阵matmul之后是一个向量，交叉熵的输入就是（向量，标签）
