### ISSUE TITLE
关于APPLE训练时间问题

### ISSUE THREAD

**Issue by Lintianjia-China** [TsingZ0/PFLlib#204]
请问我其他方法训练时间都挺正常，fedfomo也不长，只有apple训练时间特别长，是否有什么参数需要修改

**Comment by TsingZ0** [comment]
并没有，计算代价巨大就是APPLE的缺陷之一，细节请阅读其原文

**Comment by Lintianjia-China** [comment]
谢谢您，还想请问一下Fedgen的参数配置怎么选。感觉默认配置的准确率有点一般，和传统联邦差不多，FedGen 应该是个性化联邦吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月30日(周五) 上午10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TsingZ0/PFLlib] 关于APPLE训练时间问题 (Issue #204)




 
并没有，计算代价巨大就是APPLE的缺陷之一，细节请阅读其原文
