### ISSUE TITLE
What is Join ratio means ? How can one print individual client accuracy !

### ISSUE THREAD

**Issue by Amrusama** [TsingZ0/PFLlib#208]
Hello,

I have two questions regarding my experiment:

1. I'm running an experiment with 10 clients using the default parameter settings, and I noticed that the joint ratio is set to 1. Could you please clarify what "Join ratio / total clients: 1/10" means? For example, in the context of running FedAvg with 10 clients, does this setting imply that only 1 client is participating in the aggregation process?

2. How can I print or retrieve the individual accuracy of each client, rather than just the overall average accuracy?

Thanks in advance for your help!

**Comment by TsingZ0** [comment]
join ratio = join clients / total clients, which means the ratio of joining client in each iteration regarding total clients, as not all clients will join FL if join ratio < 1.
