### ISSUE TITLE
AUC 的指标计算

### ISSUE THREAD

**Issue by yu-4041** [TsingZ0/PFLlib#209]
![image](https://github.com/user-attachments/assets/8fcad9ce-fe58-4b69-a0c0-44a5b101cf70)
这里AUC指标的计算是不是存在问题？
应该使用真值和概率值来计算AUC，但代码中使用的是模型输出的logits

**Comment by TsingZ0** [comment]
这里不是在计算AUC指标，这里只是统计真值和概率值

**Comment by yu-4041** [comment]
134行计算auc的输入y_prob和y_true。  对于y_prob应该使用softmax后的output，但代码没有进行softmax而是直接使用了output

**Comment by TsingZ0** [comment]
`roc_auc_score`的使用方法请参考[手册](https://scikit-learn.org/1.5/modules/generated/sklearn.metrics.roc_auc_score.html)：Both probability estimates and non-thresholded decision values can be provided
