### ISSUE TITLE
FedGen配置

### ISSUE THREAD

**Issue by Lintianjia-China** [TsingZ0/PFLlib#211]
请问一下Fedgen的参数配置怎么选。感觉默认配置的准确率有点一般，和传统联邦差不多，FedGen 应该是个性化联邦吧

**Comment by tuichong** [comment]
> 请问一下Fedgen的参数配置怎么选。感觉默认配置的准确率有点一般，和传统联邦差不多，FedGen 应该是个性化联邦吧

你好，请问你在实现FedGen时采用的怎样的参数配置能够有较好的准确率呢？
