### ISSUE TITLE
How to start simulating 的配置问题

### ISSUE THREAD

**Issue by Bang0518** [TsingZ0/PFLlib#219]
目前的教程中首先需要Create proper environments，其次才是clone repo。但是conda env的创建依赖于repo中的yaml文件，顺序是否应该调整为：
- git clone repo
- create env by .yaml in repo

**Comment by Bang0518** [comment]
append： 运行main.py的代码应修改为
```
python main.py -data MNIST -m CNN -algo FedAvg -gr 2000 -did 0 # using the MNIST dataset, the FedAvg algorithm, and the 4-layer CNN model
```
原代码指定-m 为cnn，因为大小写原因会导致抛出NotImplementedError的错误

**Comment by Bang0518** [comment]
suggest：
- .yaml文件中未指定python版本，在创建conda环境时会出现```AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?```的错误，原因是默认使用了python3.13版本，而[在3.12之后版本中会出现此问题](https://github.com/pypa/pip/issues/12179)，建议指定python版本为3.11或者3.10
- generate_minist,py中，由于 NumPy 2.x 版本与 PyTorch 及 torchvision 不兼容，因为这些库目前还依赖于 NumPy 1.x 系列，建议降级为npmpy 1.x版本。

hotfix：在yaml文件中新增
```
dependencies:
  - python=3.11
  - numpy<2
```

**Comment by TsingZ0** [comment]
Updated.
