### ISSUE TITLE
奇怪的现象

### ISSUE THREAD

**Issue by WEISYING520** [TsingZ0/PFLlib#222]
我分别在服务器上和自己的笔记本上运行，服务器是两张3080  笔记本是1650显卡，然而发现相同的设置在笔记本上反而运行得更快一点，这是为啥呀，是应为cpu的因素吗？

**Comment by TsingZ0** [comment]
因素有很多，跟磁盘、内存、cpu都有关

**Comment by WEISYING520** [comment]
明白

**Comment by WEISYING520** [comment]
哥，我想问问，代码中FedProto是不是没有模型异构的情况，我看所有client都复制的args.model
