### ISSUE TITLE
关于 cifar10 fedavg 结果的一些问题，请您解惑

### ISSUE THREAD

**Issue by xiuguangLi** [TsingZ0/PFLlib#223]
我采用您的设置，进行的数据分配。（python generate_Cifar10.py noniid - dir）practical 设置。
![image](https://github.com/user-attachments/assets/3f53d916-120b-43b1-a1e8-ffeb49b903e6)
train 的各个客户端的数据分布如图所示。
我用您的库中的 Fedavg 进行了实验。
主要参数如下：
model：resnet18
num_clients：20
gr：1000

Fedavg 的结果是 71%，您论文中的 Fedavg 的结果是59.16%。是我哪里设置错了吗？
另外，基于 FedAvg 的代码中，去掉Server端中的  self.send_models() 以模拟 local ，得到的结果是 86%。
您的论文中没有提供关于 local 的数据结果，这个我不知道是否正确。请您指教，感谢！

**Comment by TsingZ0** [comment]
论文中的结果是基于早期PFLlib的，根据社区的需求，PFLlib会不断更新，请以最新的PFLlib实验结果为准

**Comment by tuichong** [comment]
> 我采用您的设置，进行的数据分配。（python generate_Cifar10.py noniid - dir）practical 设置。 ![image](https://private-user-images.githubusercontent.com/143073975/388346899-3f53d916-120b-43b1-a1e8-ffeb49b903e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwODM0NDMsIm5iZiI6MTczNjA4MzE0MywicGF0aCI6Ii8xNDMwNzM5NzUvMzg4MzQ2ODk5LTNmNTNkOTE2LTEyMGItNDNiMS1hMWU4LWZmZWI0OWI5MDNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQxMzE5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjBmYzA4OTk5NzY3MTA5NmU2ZGFmYjhkYjVmMWE2OWU2NzI3YzMyYWQ4NWEwNDEwZDU3OTlhMGFlYTgwYjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SFDz4bTIW8Kk1VTr2GMH3hG68shOlgPiF3Br5yuuJiA) train 的各个客户端的数据分布如图所示。 我用您的库中的 Fedavg 进行了实验。 主要参数如下： model：resnet18 num_clients：20 gr：1000
> 
> Fedavg 的结果是 71%，您论文中的 Fedavg 的结果是59.16%。是我哪里设置错了吗？ 另外，基于 FedAvg 的代码中，去掉Server端中的 self.send_models() 以模拟 local ，得到的结果是 86%。 您的论文中没有提供关于 local 的数据结果，这个我不知道是否正确。请您指教，感谢！

local的数据结果应该没问题。
