### ISSUE TITLE
关于 PFLlib 中 FedPHP 代码可能有误的问题

### ISSUE THREAD

**Issue by beyond-123** [TsingZ0/PFLlib#224]
看了下 PFLlib 中 FedPHP 的实现代码，觉得可能存在以下几点问题：
1. clientphp.py 中 self.model_s 的作用是 copy 每一轮的 global_model (line77-78)，并且在客户端本地训练的 MMD 中指导本地模型训练(line 60)；而 FedPHP论文中表述的是用 HPM 做知识迁移；两者不一样；
2. FedPHP 论文中表述的是每一轮通信中用客户端的 self.model 去接收 服务器发送的 global_model，然后用 HPM 做知识迁移指导本地 self.model 训练得到个性化模型，接着用训练后的个性化模型去更新 HPM；而 clientphp.py 中是用 global_model 更新 self.model (line 80-81)，接着在本地训练中用 global_model 给 self.model 做知识迁移（如上第1点），没有发现 HPM 模块。

为此针对 clientphp.py 提出以下几点代码修改：
1. line32-34 将 self.model_s 换为 self.model_p，代表 HPM；
2. line60 和 line100 的 self.model_s 换为 self.model_p，用HPM做知识迁移；
3. set_parameters 函数修改如下：
```
def set_parameters(self, model, R):
    self.round = R
    for new_param, old_param in zip(model.parameters(), self.model.parameters()):
        old_param.data = new_param.data.clone()
```
5. train函数中line63 后面添加下面代码，用于更新 HPM
```
mu = self.mu * self.round
for new_param, old_param in zip(self.model.parameters(), self.model_p.parameters()):
    old_param.data = new_param * (1 - mu) + old_param * mu
```

**Comment by TsingZ0** [comment]
已修改，请查看最新版
