### ISSUE TITLE
Why use "best mean testing accuracy" instead of "last mean testing accuracy" in personalized FL?

### ISSUE THREAD

**Issue by neko941** [TsingZ0/PFLlib#226]
Hi, I have a question regarding the evaluation metric used in the final results of the implementation.

In traditional federated learning, it’s common to report the last test accuracy of the global model after training completes. However, I noticed that in this implementation of personalized federated learning, the metric used is the best mean testing accuracy across clients.

Could you clarify why "best mean testing accuracy" was chosen instead of "last mean testing accuracy"? 

Thank you

**Comment by TsingZ0** [comment]
Personalized models in pFL are more prone to overfitting. By using early stopping, we can capture the best accuracy, making reporting the highest mean testing accuracy reasonable.

**Comment by neko941** [comment]
thank you for your answer
